config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  root 'pages#home'
  resources :posts
  resources :adopts
  resources :animals
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:destroy, :update]    
  get '/dashboard' => 'admin#dashboard', as: "dashboard"
  get '/history' => 'pages#history', as: 'history'
  get '/requests/:id' => 'pages#requests', as: 'requests'
  get '/admin/register' => 'admin#new', as: 'register'
  get '/user/new' => 'users#new', as: 'new_user' 
  get '/user/:id' => 'users#edit', as: 'edit_user' 
  post '/user/create' => 'users#create', as: 'create_user' 
  get '/cat' => 'pages#cat', as: 'cat'
  get '/dog' => 'pages#dog', as: 'dog'
  get '/contactus' => 'pages#contact', as: 'contact'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admin/dashboard.html.erb
<div class="container mt-5">
  <h1>ADMIN DASHBOARD</h1>
  <div class="mb-4">
    <%= link_to 'Create New User', new_user_path, class: "btn btn-success" %>
    <%= link_to "New Animal", new_animal_path, class: "btn btn-info" %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="admin-table-container bg-white p-4">
        <h2 class="text-center">Manage Users</h2>
        <table class="table border border-dark">
          <thead class="bg-dark text-white">
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Contact details</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.contact %></td>
                <td>
                  <div class="d-flex justify-content-evenly">
                    <%= link_to "Edit", edit_user_path(user), class: "btn btn-primary" %>
                    <%= button_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <div class="admin-table-container bg-white p-4">
        <h2 class="text-center">Manage Pets</h2>
        <table class="table border border-dark">
          <thead class="bg-dark text-white">
            <tr>
              <th>Name</th>
              <th>Species</th>
              <th>Owner's Email</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @pets.each do |pet| %>
              <tr>
                <td><%= pet.name %></td>
                <td><%= pet.species %></td>
                <td><%= pet.user.email %></td>
                <td>
                  <div class="d-flex justify-content-evenly">
                    <%= link_to "Edit", edit_animal_path(pet), class: "btn btn-primary" %>
                    <%= button_to "Delete", animal_path(pet), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/new.html.erb
<h2>Create a New User</h2>
<%= form_for @user, url: admin_users_path do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Create User' %>
<% end %>

app/views/admin/register.html.erb
<h2>Register new user</h2>

<%= form_for(@resource, as: @resource_name, url: registration_path(@resource_name), html: { class: "form-signin" }) do |f| %>
  <%= render "devise/shared/error_messages", resource: @resource %>

  <div class="form-floating">
    <%= f.label :email, class: "visually-hidden" %>
    <%= f.email_field :email, class: "form-control", autofocus: true, autocomplete: "email", placeholder: "Email address" %>
  </div>

  <div class="form-floating">
    <%= f.label :name, class: "visually-hidden" %>
    <%= f.text_field :name, class: "form-control", autofocus: true, autocomplete: "name", placeholder: "Name" %>
  </div>

  <div class="form-floating">
    <%= f.label :password, class: "visually-hidden" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, class: "form-control", autocomplete: "new-password", placeholder: "Password" %>
  </div>

  <div class="form-floating">
    <%= f.label :password_confirmation, class: "visually-hidden" %>
    <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "new-password", placeholder: "Confirm Password" %>
  </div>

  <div class="checkbox mb-3">
    <label>
      <%= f.check_box :remember_me %> Remember me
    </label>
  </div>

  <div class="text-center">
    <%= f.submit "Sign up", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>