config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  root 'pages#home'
  resources :posts
  resources :adopts
  resources :animals
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:destroy, :update]    
  get '/dashboard' => 'admin#dashboard', as: "dashboard"
  get '/history' => 'pages#history', as: 'history'
  get '/requests/:id' => 'pages#requests', as: 'requests'
  get '/admin/register' => 'admin#new', as: 'register'
  get '/user/new' => 'users#new', as: 'new_user' 
  get '/user/:id' => 'users#edit', as: 'edit_user' 
  post '/user/create' => 'users#create', as: 'create_user' 
  get '/cat' => 'pages#cat', as: 'cat'
  get '/dog' => 'pages#dog', as: 'dog'
  get '/contactus' => 'pages#contact', as: 'contact'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/_banner.html.erb
<div class="banner-nav d-flex justify-content-evenly pt-3">
    <p> <%= link_to "CATS & KITTENS", cat_path, class: "text-decoration-none text-white a" %> </p>
    <p> <%= link_to "DOGS & PUPPEIS", dog_path, class: "text-decoration-none text-white a" %> </p>
    <p> <%= link_to "ALL PET", animals_path, class: "text-decoration-none text-white a" %> </p>
</div>
<div class="banner d-flex align-items-center justify-content-center ">
    <div class="text-center text-light  fw-bolder text-shadow ">
        <h1> Adopt a Lifetime of Happiness </h1>
        <h2>- Help Us Give Shelter -</h3>
    </div>
</div>

app/views/pages/_banner2.html.erb
<div class="banners container-full vh-50">
    <div class="d-flex align-items-center justify-content-center bg-white">
        <div >
            <h1 class="text-center py-5 fw-bolder home-text2 "> PLANNING TO ADOPT A PET? </h1>
            <h3 class="home-text2 text-center"> Adopting a pet is a heartwarming experience, but it's also a big responsibility. <br> With careful planning and consideration, you can provide a loving and secure home for a new addition to your family.<br> Your future pet is waiting for you with wagging tails and purring affection <br>– are you ready to make a difference in their life? </h3>
            <p class="text-center">
            <%= link_to "Start Adopting Now", animals_path, class: "btn btn-primary p-2 mt-2 rounded"  %>
            </p>
        </div>
    </div>
</div>

app/views/pages/_banner3.html.erb
<div class="container home-cont1">
  <div class="row justify-content-center align-items-center">
      <div class="col-10 col-sm-5 col-md-3 col-lg-2 overflow-hidden">
      <%= link_to cat_path, class:"text-decoration-none text-dark fw-bold " do %>
        <div class=" bg-white mt-4 d-flex flex-column align-items-center abc shadow-sm">
          <%= image_tag "cat.png", class: "img" %>
          <p class="text-center"> CAT </p>
        </div>
        <% end %>
      </div>
    

    
      <div class="col-10 col-sm-5 col-md-3 col-lg-2 overflow-hidden">
      <%= link_to dog_path, class:"text-decoration-none text-dark fw-bold " do %>
        <div class="bg-white mt-4 d-flex flex-column align-items-center abc shadow-sm">
          <%= image_tag "dog.png", class: "img" %>
          <p class="text-center  text-dark"> DOG </p>
        </div>
        <% end %>
      </div>
    

    
      <div class="col-10 col-sm-5 col-md-3 col-lg-2 overflow-hidden">
      <%= link_to animals_path, class:"text-decoration-none text-dark fw-bold" do %>
        <div class="bg-white mt-4 d-flex flex-column align-items-center abc shadow-sm">
          <%= image_tag "cat.png", class: "img" %>
          <p class="text-center"> ALL </p>
        </div>
        <% end %>
      </div>
    
  </div>
</div>

app/views/pages/cat.html.erb
<%= render "pages/banner" %>
<div class="container mt-4">
<h1>Cats & Kittens</h1>
  <div class="row">
    <% @cat.each do |animal| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      
        <%= link_to animal_path(animal), class: "text-decoration-none text-dark" do %>
          <div class="container-wrapper">
          
            <div class="border border-primary rounded mt-4 tryme">
              <div id="<%= dom_id animal %>">
                <div class="img-container">
                  <% if !animal.image.present? %>
                    <%= image_tag("dog.jpg", class: "image") %>
                  <% else %>
                    <%= image_tag(animal.image, class: "image") %>
                  <% end %>
                </div>
                <div class="p-2 cont">
               
                  <h3 class="d-flex justify-content-center">
                    <%= animal.name %>
                  </h3>
                  <div class="d-flex justify-content-around">
                    <p>
                      <%= animal.breed %>
                      <%if animal.is_adopted %>
                        <p> Adopted </p>
                      <% else %>
                        <p> Available for Adoption </p>  
                      <% end %>
                    </p>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="">
  <div class="container mt-5 p-5 shadow contact-cont">
    <h1>Contact Us</h1>
    <p>Thank you for considering reaching out to us. At HUGS, we value your feedback, inquiries, and suggestions. We are here to assist you in any way we can.</p>
    <br>
    <h3>General Inquiries:</h3>
    <p>For general questions, information about our services, or any other non-urgent matters, please feel free to contact us by leaving a message below.</p>

     <div class="form-group" id="text-area-container">
    <textarea class="form-control" id="message" rows="4" placeholder="Enter your inquiry here"></textarea>
    <%= link_to "Send Message", root_path, class: "btn btns btn-primary m-2" %>
    </div>
   <br><hr>

    <h3>Adoption and Pet-related Questions:</h3>
    <p>If you have specific questions about pet adoption, our available animals, or the adoption process and for personalized assistance, you can also contact our adoption specialists at <a href="mailto:adoption@hugsadoptionapp.com" class="text-white" >adoption@hugsadoptionapp.com</a>.</p>

    
  </div>
  </div>

app/views/pages/dashboard.html.erb
<h1> ADMIN DASHBOARD </h1>

<%= link_to "Create new user", new_user_registration_path %>

app/views/pages/dog.html.erb
<%= render "pages/banner" %>

<div class="container  p-5 rounded">
<h1>Dogs & Puppies</h1> 
  <div class="row">
    <% @dog.each do |animal| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      
        <%= link_to animal_path(animal), class: "text-decoration-none text-dark" do %>
          <div class="container-wrapper">
          
            <div class="border border-primary rounded mt-4 tryme">
              <div id="<%= dom_id animal %>">
                <div class="img-container">
                  
                  <% if !animal.image.present? %>
                    <%= image_tag("dog.jpg", class: "image") %>
                  <% else %>
                    <%= image_tag(animal.image, class: "image") %>
                  <% end %>
                </div>
                <div class="p-2 cont">
               
                  <h3 class="d-flex justify-content-center">
                    <%= animal.name %>
                  </h3>
                  <div class="d-flex justify-content-around">
                    <p>
                      <%= animal.breed %>
                      
                    </p>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/history.html.erb
<p style="color: green"><%= notice %></p>

<div class="container  p-5 rounded bg-white mt-2 shadow">
<div>
  <h1>Pet Adoption Listings</h1>  
<% if @for_adoption.present? %>  
  <%= link_to "Add pet for adoption", new_animal_path, class: "btn btn-secondary" %>
</div>  
<div class="container mt-4">
  <div class="row">
    <% @for_adoption.each do |animal| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      
        <%= link_to animal_path(animal), class: "text-decoration-none text-dark" do %>
          <div class="container-wrapper">
          
            <div class="border border-primary rounded mt-4 tryme">
              <div id="<%= dom_id animal %>">
                <div class="img-container">
                  <% if animal.adopts.pending.count > 0 %>
                    <div class="notification-badge">
                      <%= animal.adopts.pending.count %>
                    </div>
                  <% end %>  
                  <% if !animal.image.present? %>
                    <%= image_tag("dog.jpg", class: "image") %>
                  <% else %>
                    <%= image_tag(animal.image, class: "image") %>
                  <% end %>
                </div>
                <div class="p-2 cont">
               
                  <h3 class="d-flex justify-content-center">
                    <%= animal.name %>
                  </h3>
                  <div class="d-flex justify-content-around">
                    <p>
                      <%= animal.breed %>
                      <%if animal.is_adopted %>
                        <p> Adopted </p>
                      <% else %>
                        <p> Available for Adoption </p>  
                      <% end %>
                    </p>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% else %>
    <p class="text-center"> No Pet Listed for Adoption </p>
    <p class="text-center">
    <%= link_to "Add pet for adoption", new_animal_path, class: "btn btn-success text-center" %>
    </p>
  <% end %>
</div>
</div>

<div class="container  p-5 rounded bg-white mt-4 shadow">
  <h1>Pet Adoption Requests</h1>
  <% if @adopts.present? %>
  <div class="container mt-4">
    <div class="row">
      <% @adopts.each do |adopt| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <%= link_to animal_path(adopt.animal), class: "text-decoration-none text-dark" do %>
            <div class="container-wrapper">
              <div class="border border-primary rounded mt-4 tryme ">
                <div id="<%= dom_id adopt.animal %>">
                  <div class="img-container">
                    
                    <% if adopt.status == 'approved' %>
                      <div class="notification-badge-approved">
                        <%= adopt.status %>
                      </div>
                    <% elsif adopt.status == 'pending'%>
                      <div class="notification-badge-pending">
                        <%= adopt.status %>
                      </div>
                    <% else %>
                      <div class="notification-badge-rejected">
                        <%= adopt.status %>
                      </div>
                    <% end %> 

                    <% if !adopt.animal.image.present? %>
                      <%= image_tag("dog.jpg", class: "image") %>
                    <% else %>
                      <%= image_tag(adopt.animal.image, class: "image") %>
                    <% end %>
                  </div>  
                  <div class="p-2 cont">
                    <h3 class="d-flex justify-content-center">
                      <%= adopt.animal.name %>
                    </h3>
                    <div class="d-flex justify-content-around">
                      <p>
                        <%= adopt.animal.breed %>
                      </p>
                      <p>
                        <%= adopt.animal.age %> mos
                      </p>
                      <p>
                        <%= adopt.status %>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% else %>
    <p class="text-center"> It's Quiet Here, No Pet Requests Yet </p>
    <p class="text-center">
    <%= link_to "Browse Pet to Adopt", animals_path, class: "btn btn-success text-center" %>
    </p>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= render 'banner' %>
<%= render 'banner3' %>
<p style="color: green"><%= notice %></p>

<div class="container mt-4 p-5">
  <h1 class="text-center">  
    <%= link_to "Pets Available for Adoption >", animals_path, class: "text-decoration-none home-text" %>
  </h1>
  <div class="row">
    <% @animals.each_with_index do |animal, index| %>
      <% if index < 4 %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <%= link_to animal_path(animal), class: "text-decoration-none text-dark" do %>
            <div class="container-wrapper">
              <div class="rounded mt-4 tryme ">
                <div id="<%= dom_id animal %>">
                  <div class="img-container">
                    <% if !animal.image.present? %>
                      <%= image_tag("dog.jpg", class: "image") %>
                    <% else %>
                      <%= image_tag(animal.image, class: "image") %>
                    <% end %>
                  </div>
                  <div class="p-2 cont">
                    <h3 class="d-flex justify-content-center">
                      <%= animal.name %>
                    </h3>
                    <div class="d-flex justify-content-around">
                      <p>
                        <%= animal.breed %>
                      </p>
                      <p>
                        <%= animal.age %> mos
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render 'banner2' %>

app/views/pages/register.html.erb
<%= render 'devise/registrations/new' %>

app/views/pages/requests.html.erb
<div class="container p-4">
  <div class="rounded bg-white shadow p-3">
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>User</th>
          <th>Date</th>
          <th>Message</th>
          <th>Status</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @adoption_requests.each do |request| %>
          <tr>
            <td><%= request.user.email %></td>
            <td><%= request.date %></td>
            <td><%= request.message %></td>
            <td><%= request.status %></td>
            <td>
              <%= form_for(request, url: adopt_path(request), method: :patch) do |f| %>
                <%= f.hidden_field :status, value: 'approved' %>
                <%= f.submit "Approve", class: "btn btn-success" %>
              <% end %>
              <%= form_for(request, url: adopt_path(request), method: :patch) do |f| %>
                <%= f.hidden_field :status, value: 'rejected' %>
                <%= f.submit "Reject", class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>