config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  root 'pages#home'
  resources :posts
  resources :adopts
  resources :animals
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:destroy, :update]    
  get '/dashboard' => 'admin#dashboard', as: "dashboard"
  get '/history' => 'pages#history', as: 'history'
  get '/requests/:id' => 'pages#requests', as: 'requests'
  get '/admin/register' => 'admin#new', as: 'register'
  get '/user/new' => 'users#new', as: 'new_user' 
  get '/user/:id' => 'users#edit', as: 'edit_user' 
  post '/user/create' => 'users#create', as: 'create_user' 
  get '/cat' => 'pages#cat', as: 'cat'
  get '/dog' => 'pages#dog', as: 'dog'
  get '/contactus' => 'pages#contact', as: 'contact'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/animal.rb
  class Animal < ApplicationRecord
    belongs_to :user
    has_many :adopts
    has_one_attached :image
  end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.where.not(user: current_user).where(is_adopted: false).order(created_at: :desc)
  end

  # GET /animals/1 or /animals/1.json
  def show
    @animal = Animal.find(params[:id])
    @adoption_requests = @animal.adopts
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Pet was successfully added to listing." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal = Animal.find(params[:id])
    @adopt = current_user.adopts.find_by(animal_id: @animal.id)
  
    if current_user.admin?
      # An admin can delete any animal
      @animal.adopts.destroy_all
      @animal.destroy
  
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: "Pet is successfully deleted from the listing" }
        format.json { head :no_content }
      end
    elsif @adopt
      # A regular user can cancel their own adoption request
      @adopt.destroy
  
      respond_to do |format|
        format.html { redirect_to animals_url, notice: "Adoption request was successfully cancelled." }
        format.json { head :no_content }
      end
    elsif @animal.user == current_user
      # A regular user can delete their own animals
      @animal.adopts.destroy_all
      @animal.destroy
  
      respond_to do |format|
        format.html { redirect_to animals_url, notice: "Pet were successfully deleted." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to animals_url, alert: "You can only cancel your own adoption requests or delete your own pet listing." }
        format.json { head :unprocessable_entity }
      end
    end
  end
  
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :species, :breed, :age, :description, :is_adopted, :user_id, :image)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal.html.erb
 <div id="<%= dom_id animal %>">

<div class="d-flex align-items-center">
  <div class="pet-container">
    <div>
      <h2><%= animal.name %></h2>
      <h6 class="text-dark"><%= animal.breed %> * Bulacan</h6>
    </div>
    <hr>
    <div>
      <% if animal.species == "cat" || animal.species == "Cat"%>
        <% if animal.age <= 11 %>
          <p> Kitten </p>
        <% else %>
          <p> Cat </p>
        <% end %>   
      <% else %>
        <% if animal.age <= 11 %>
          <p> Puppy </p>
        <% else %>
          <p> Dog </p>
        <% end %>   
      <% end %> 
    </div>
    <hr>
    <div>
      <h3>About</h3>
      <h6>Characteristics</h6>
      <p><%= animal.description %></p>
    </div>
  </div>
  <div >
  <div class="img-animal d-flex flex-column align-items-center p-2">
    <div class="pet-img">
      <% if !animal.image.present? %>
        <%= image_tag("dog.jpg", class: "image") %>
      <% else %>
        <%= image_tag(animal.image, class: "image") %>
      <% end %>
    </div> 
        <div>
          <% if current_user && current_user.email == animal.user.email %>
            <p>  <%= animal.name %> is adopted outside the app? </p>
          <% else %>

          <p> Interested to adopt <%= animal.name %>? </p>
          <% end %>
        </div>
    <div>
      <% if current_user %>
        <% if current_user.id == @animal.user_id %>
        <div class="d-flex ">
          <%= link_to 'Edit', edit_animal_path(@animal), class: 'btn btn-primary m-1' %>
          <%= button_to 'Delete from listing', @animal, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger m-1' %>
        </div>
        <% else %>
         <% if current_user.adopts.exists?(animal_id: @animal.id) %> 
            <% request = current_user.adopts.find_by(animal_id: @animal.id) %>
            <% if request.status == 'approved' %>
              <h4 class="btn btn-success"> Adopted </h4>
            <% else %>
              <%= button_to 'Cancel Adoption', request, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>


          <% else %>
            <p>
              <%= link_to 'Adopt', new_adopt_path(animal_id: @animal.id), class: 'btn btn-info' %>
            </p>
          <% end  %>  
        <% end %>
      <% else %>
          <div>
            <%= link_to "Sign up",  new_user_registration_path, class: "btn btn-outline-light" %>
          </div>
          
      <% end %>
      </div>


    </div> 
  </div>
</div>

<% if  @adoption_requests.present?  %>
<%if current_user && current_user.id == animal.user_id %>

 <div class="container p-4">
  <div class="rounded bg-white shadow p-3">
    <h1 class="text-center"> Adoption Requests </h1>
      <table class="table table-bordered .dark-table">
        <thead class="thead-dark dark-table">
          <tr>
            <th>User</th>
            <th>Date</th>
            <th>Message</th>
            <th>Status</th> 
            <th>Action</th>
             <% if @adoption_requests.any? { |request| request.status == 'approved' } %>
            <th>Contact</th>
          <% end %>
          </tr>
        </thead>
        <% @adoption_requests.each do |request| %>
        <tbody>
          <tr>
            <td><%= request.user.email %></td>
            <td><%= request.date %></td>
            <td><%= request.message %></td>
            <td><%= request.status %></td>
            <td>
              <% if request.status != 'pending' %>
                <p class="text-danger text-center fw-bold"> X </p>
              <% else %>
                <%= form_for(request, url: adopt_path(request), method: :patch) do |f| %>
                  <%= f.hidden_field :status, value: 'approved' %>
                  <%= f.submit "Approve", class: "btn btn-success" %>
                <% end %>
                <%= form_for(request, url: adopt_path(request), method: :patch) do |f| %>
                  <%= f.hidden_field :status, value: 'rejected' %>
                  <%= f.submit "Reject", class: "btn btn-danger" %>
                <% end %>
              <% end %>
            </td>
            <% if request.status == 'approved' %>
              <td colspan="5">
                <%= request.user.contact %>
              </td>
           
          <% end %>
          </tr>
          
        </tbody>
        <% end %>
      </table>
    
  </div>
</div>

<% end %>
<% end %>

app/views/animals/_form.html.erb
<div class="container my-5 bg-white rounded shadow">
  <div class="row">
    <div class="col-md-5">
      <%= image_tag "https://img.freepik.com/free-vector/adopt-pet-concept_23-2148523582.jpg?w=1060&t=st=1697989685~exp=1697990285~hmac=299735a22b453b63b64293a37f4e6dafd605401ceb01ac98dd9cef529d60901b", alt: "Adopt Pet", class: "img-fluid" %>
    </div>

    <div class="col-md-7 p-4">
      <div class="container">
        <h1 class ="text-center">Your Pet's Next Home Awaits:<br> Create an Adoption Listing</h1>
        <%= form_with(model: animal, class: "animal-form") do |form| %>
          <% if animal.errors.any? %>
            <div class="alert alert-danger">
              <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>
              <ul>
                <% animal.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name, "Pet's name" %>
            <%= form.text_field :name, class: "form-control", required: true %>
          </div>

          <div class = "form-group">
            <%= form.label :species, "Pet type (eg. cat, dog)" %>
            <%= form.text_field :species, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :breed %>
            <%= form.text_field :breed, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :age %>
            <%= form.number_field :age, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= form.label :image, "Choose image" %> <br>
            <%= form.file_field :image, class: "form-control-file" %>
          </div>

          <br>  
          <div class="form-group">
            <%= form.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/edit.html.erb
<h1 class="text-center pt-5">Edit Pet</h1>

<%= render "form", animal: @animal %>

app/views/animals/index.html.erb
<%= render "pages/banner" %>
<p style="color: green"><%= notice %></p>
<div class="container  p-5 rounded bg-white">
<h1>Available pet for adoption</h1>
<% if current_user %>
  <%= link_to "Add pet for adoption", new_animal_path, class:"btn btn-dark" %>
<% end %>
<div class="container mt-4">
  <div class="row">
    <% @animals.each do |animal| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <%= link_to animal_path(animal),class: "text-decoration-none text-dark" do %>
          <div class="container-wrapper">

          <div class="rounded mt-4 tryme ">

            <div id="<%= dom_id animal %>">
            <div class="img-container">
              <% if !animal.image.present? %>
                  <%= image_tag("dog.jpg", class: "image") %>
                <% else %>
                  <%= image_tag(animal.image, class: "image") %>
                <% end %>
            </div>  
              <div class="p-2 cont">
                  <h3 class="d-flex justify-content-center">
                    <%= animal.name %>
                  </h3>
                  <div class="d-flex justify-content-around">
                    <p>
                      <%= animal.breed %>
                    </p>
                    <p>
                      <%= animal.age %> mos
                    </p>
                  </div>
            </div>
            </div>
          </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


</div>

app/views/animals/new.html.erb
<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @animal %>