config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  root 'pages#home'
  resources :posts
  resources :adopts
  resources :animals
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:destroy, :update]    
  get '/dashboard' => 'admin#dashboard', as: "dashboard"
  get '/history' => 'pages#history', as: 'history'
  get '/requests/:id' => 'pages#requests', as: 'requests'
  get '/admin/register' => 'admin#new', as: 'register'
  get '/user/new' => 'users#new', as: 'new_user' 
  get '/user/:id' => 'users#edit', as: 'edit_user' 
  post '/user/create' => 'users#create', as: 'create_user' 
  get '/cat' => 'pages#cat', as: 'cat'
  get '/dog' => 'pages#dog', as: 'dog'
  get '/contactus' => 'pages#contact', as: 'contact'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= image_tag("logo2.png", width: "280", height: "120")  %>
    <div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item" >
          <%= link_to "Home", root_path, class: "nav-link text" %>
        </li>
        <li class="nav-item">
          <%= link_to "Find a pet", animals_path, class: "nav-link text" %>
        </li>
        <% if current_user && current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link text" %>
          </li>
        <% end %>  
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "History", history_path, class: "nav-link text" %>
          </li>
        <% end %> 
        <li class="nav-item">
          <%= link_to "Contact Us", contact_path, class: "nav-link text" %>
        </li> 
      </ul>
      </div>
    </div>
    <div class="text-decoration-none">
      <% if current_user%>
        <div class="d-flex">
          <div class="p-1">
          <%= current_user.email %>
          </div>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </div>  
      <% else %>
        <%= link_to "Register", new_user_registration_path, class: "btn btn-outline-primary" %>
        <%= link_to "Login",  new_user_session_path, class: "btn btn-success" %>
      <% end %>  
    </div>
  </div>
</nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div>
  <div>
  <%= render "layouts/nav" %>
  
  </div>
    <%= yield %>
    <div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>